# Generated by Django 4.0.4 on 2022-07-31 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_datetime_alter_comment_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 12, 43, 0, 173238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 12, 43, 0, 173526, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 12, 43, 0, 172435, tzinfo=utc)),
        ),
    ]
